name: buku
description: "LEARNSTAR DEEPNET LABS."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.1
  syncfusion_flutter_pdfviewer: ^23.2.4
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  fl_chart: ^0.65.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true
  assets:
    - images/
    - images/sample.pdf



# launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
